spring:
  application:
    name: sub_tech_challenge_api
  datasource:
    url: jdbc:postgresql://challenge.ctmuyuogk8tb.us-east-2.rds.amazonaws.com/challenge
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres2
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-iugtbtykhkw0lt8h.us.auth0.com/
